create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique not null,
  password_hash text not null,
  role text not null default 'user',
  created_at timestamptz not null default now()
);

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  title text not null,
  username text not null,
  user_id bigint references public.users(id) on delete cascade,
  storage_path text not null,
  audio_url text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.tracks enable row level security;

-- The Flask backend uses the Supabase service-role key.
-- Do NOT expose that key in browser JavaScript.
-- For this MVP, browser access is through Flask only.
